version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - course-management-network

  # Backend Service
  backend:
    build: ./backend
    container_name: course-management-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/courseManagementSystem
      - PORT=5000
      - NODE_ENV=production
    networks:
      - course-management-network

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: course-management-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - course-management-network

networks:
  course-management-network:
    driver: bridge

volumes:
  mongodb_data:
